### ISSUE TITLE
[BUG] now.getUTCDate) missing brackets ()

### ISSUE THREAD

**Issue by nicopret1** [dirkjanfaber/node-red-contrib-eskomsepush#11]
**Describe the bug**
I think there might be an error in the code on line 293:
`    if (new Date(EskomSePushInfo.calc.next.start).getUTCDay() !== now.getUTCDate) {`

It should be:
`    if (new Date(EskomSePushInfo.calc.next.start).getUTCDay() !== now.getUTCDate()) {`

**To Reproduce**
1. Using node  'eskomsepush'
3. See error
I've seen issues where the status colour were not updated correctly after I switched between "test" and "active" modes.

**Expected behavior**
Status colour should be updated to green if all working and switched from test to active.

**Screenshots**

**Flow**
If applicable, add a flow to help explain your problem.

**Software (please complete the following information):**
 - node-red-contrib-eskomsepush version: v0.0.15

**Additional context**

**Comment by dirkjanfaber** [comment]
Just released version 0.0.17 (was a bit hasty with 0.0.16, hence the jump).
