### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ChristoffelG** [dirkjanfaber/node-red-contrib-eskomsepush#5]
**Describe the bug**
Seemingly internal TypeError

**To Reproduce**
The node was working fine and it started giving issues without me touching it again.
I stopped referencing it and its still giving errors

**Expected behavior**
Output time to next LS and duration

**Software (please complete the following information):**
 - node-red-contrib-eskomsepush version: 0.0.12

**Comment by ChristoffelG** [comment]
It gives this error: "TypeError: dates.stages[EskomSePushInfo.calc.stage] is not iterable"

**Comment by HSPilot2008** [comment]
Having the same issue

> It gives this error: "TypeError: dates.stages[EskomSePushInfo.calc.stage] is not iterable"

**Comment by dirkjanfaber** [comment]
Can I get some info on the area are you using?

**Comment by ChristoffelG** [comment]
It looks like the issue happens when you leave it on test for a while. When I disable test for a few minutes the error stops.

**Comment by HSPilot2008** [comment]
> It looks like the issue happens when you leave it on test for a while. When I disable test for a few minutes the error stops.

My test option is disabled for 30 mins now. Still the same

**Comment by ChristoffelG** [comment]
> Can I get some info on the area are you using?

Im in erasmusrand

**Comment by HSPilot2008** [comment]
> Can I get some info on the area are you using?

jhbcitypower2-8-sundowner

**Comment by dirkjanfaber** [comment]
Thanks. I am able to reproduce the issue.

**Comment by dirkjanfaber** [comment]
Created a new release, fixing this. Should be updatable from the palette manager shortly.
